/**
 * @file Common.hpp
 * @author Tomáš Ludrovan
 * @brief Common definitions
 * @version 0.1
 * @date 2024-01-28
 * 
 * @copyright Copyright (c) 2024
 * 
 */

#ifndef COMMON_HPP
#define COMMON_HPP

/**
 * @brief Editor object ID.
 * 
 * @details This type is used for identifying editor objects -- players and
 *          obstacles. Each object shall have its own unique OID generated by
 *          generateEditorOID() function. A special value of EDITOR_OID_NULL
 *          shall be used in the manner of the `NULL` pointer in C and C++.
 */
typedef size_t EditorOID;

// Number of units taken by half of a player sprite in the editor
constexpr double EDITOR_PLAYER_RADIUS = 50.0;

constexpr EditorOID EDITOR_OID_NULL = 0;

/**
 * @brief Generates a unique editor object identifier.
 */
inline EditorOID generateEditorOID()
{
	static EditorOID lastOID = 0;
	lastOID++;
	return lastOID;
}

#endif // COMMON_HPP
